laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('perfil/equipe', ['as' => 'perfil.equipe', 'uses' => 'PerfilController@equipe']);
Route::get('perfil', ['as' => 'perfil', 'uses' => 'PerfilController@index']);
Route::get('projetos/{projetos_categoria_slug?}', ['as' => 'projetos', 'uses' => 'ProjetosController@index']);
Route::get('imprensa', ['as' => 'imprensa', 'uses' => 'ClippingController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);
    Route::resource('equipe', 'EquipeController');
    Route::resource('banners', 'BannersController');
    Route::resource('perfil', 'PerfilController');
    Route::resource('projetos/categorias', 'ProjetosCategoriasController');
    Route::resource('projetos', 'ProjetosController');
    Route::get('projetos/{projetos}/imagens/clear', [
        'as'   => 'painel.projetos.imagens.clear',
        'uses' => 'ProjetosImagensController@clear'
    ]);
    Route::resource('projetos.imagens', 'ProjetosImagensController');
    Route::resource('clipping/imagem', 'ClippingImagemFixaController');
    Route::resource('clipping', 'ClippingController');
    Route::get('clipping/{clipping}/imagens/clear', [
        'as'   => 'painel.clipping.imagens.clear',
        'uses' => 'ClippingImagensController@clear'
    ]);
    Route::resource('clipping.imagens', 'ClippingImagensController');
    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');
    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannerRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'imagem1' => [
            'width'  => 1980,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/banners/1/'
        ],
        'imagem2' => [
            'width'  => 720,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/banners/2/'
        ]
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannerRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem1'] = CropImage::make('imagem1', $this->image_config['imagem1']);
            $input['imagem2'] = CropImage::make('imagem2', $this->image_config['imagem2']);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannerRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem1'])) $input['imagem1'] = CropImage::make('imagem1', $this->image_config['imagem1']);
            if (isset($input['imagem2'])) $input['imagem2'] = CropImage::make('imagem2', $this->image_config['imagem2']);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Helpers\CropImage;

class ClippingController extends Controller
{
    private $image_config = [
        [
            'width'   => 165,
            'height'  => 220,
            'path'    => 'assets/img/clipping/thumbs/'
        ]
    ];

    public function index()
    {
        $clipping = Clipping::ordenados()->get();

        return view('painel.clipping.index', compact('clipping'));
    }

    public function create()
    {
        return view('painel.clipping.create');
    }

    public function store(ClippingRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Clipping::create($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar clipping: '.$e->getMessage()]);

        }
    }

    public function edit(Clipping $clipping)
    {
        return view('painel.clipping.edit', compact('categorias', 'clipping'));
    }

    public function update(ClippingRequest $request, Clipping $clipping)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $clipping->update($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar clipping: '.$e->getMessage()]);

        }
    }

    public function destroy(Clipping $clipping)
    {
        try {

            $clipping->delete();
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir clipping: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagemFixaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingImagemFixaRequest;
use App\Http\Controllers\Controller;

use App\Models\ClippingImagemFixa;
use App\Helpers\CropImage;

class ClippingImagemFixaController extends Controller
{
    private $image_config = [
        'width'  => null,
        'height' => 1280,
        'path'   => 'assets/img/clipping/'
    ];

    public function index()
    {
        $imagem = ClippingImagemFixa::first();

        return view('painel.clipping.imagem', compact('imagem'));
    }

    public function update(ClippingImagemFixaRequest $request, ClippingImagemFixa $imagem)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $imagem->update($input);
            return redirect()->route('painel.clipping.imagem.index')->with('success', 'Imagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Models\ClippingImagem;
use App\Helpers\CropImage;

class ClippingImagensController extends Controller
{
    private $image_config = [
        [
            'width'   => 180,
            'height'  => 180,
            'path'    => 'assets/img/clipping/imagens/thumbs/'
        ],
        [
            'width'   => 1980,
            'height'  => null,
            'upsize'  => true,
            'path'    => 'assets/img/clipping/imagens/'
        ]
    ];

    public function index(Clipping $clipping)
    {
        $imagens = ClippingImagem::clipping($clipping->id)->ordenados()->get();

        return view('painel.clipping.imagens.index', compact('imagens', 'clipping'));
    }

    public function show(Clipping $clipping, ClippingImagem $imagem)
    {
        return $imagem;
    }

    public function create(Clipping $clipping)
    {
        return view('painel.clipping.imagens.create', compact('clipping'));
    }

    public function store(Clipping $clipping, ClippingImagemRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            $input['clipping_id'] = $clipping->id;

            $largura = getimagesize(asset('assets/img/clipping/imagens/'.rawurlencode($input['imagem'])))[0];
            $altura = getimagesize(asset('assets/img/clipping/imagens/'.rawurlencode($input['imagem'])))[1];

            if ($largura <= 0 || $altura <= 0) {
                throw new Exception('Não foi possível identificar as medidas da imagem.');
            }

            $imagem = ClippingImagem::create($input);
            $imagem->largura = $largura;
            $imagem->altura = $altura;
            $imagem->save();

            $view = view('painel.clipping.imagens.imagem', compact('clipping', 'imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Clipping $clipping, ClippingImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }

    public function clear(Clipping $clipping)
    {
        try {

            $clipping->imagens()->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagens excluídas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EquipeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EquipeRequest;
use App\Http\Controllers\Controller;

use App\Models\Equipe;
use App\Helpers\CropImage;

class EquipeController extends Controller
{
    private $image_config = [
        'width'  => 150,
        'height' => 150,
        'path'   => 'assets/img/equipe/'
    ];

    public function index()
    {
        $registros = Equipe::ordenados()->get();

        return view('painel.equipe.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.equipe.create');
    }

    public function store(EquipeRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Equipe::create($input);
            return redirect()->route('painel.equipe.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Equipe $registro)
    {
        return view('painel.equipe.edit', compact('registro'));
    }

    public function update(EquipeRequest $request, Equipe $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $registro->update($input);
            return redirect()->route('painel.equipe.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Equipe $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.equipe.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/PerfilController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PerfilRequest;
use App\Http\Controllers\Controller;

use App\Models\Perfil;
use App\Helpers\CropImage;

class PerfilController extends Controller
{
    private $image_config = [
        'width'  => 1280,
        'height' => null,
        'path'   => 'assets/img/perfil/'
    ];

    public function index()
    {
        $perfil = Perfil::first();

        return view('painel.perfil.index', compact('perfil'));
    }

    public function update(PerfilRequest $request, Perfil $perfil)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $perfil->update($input);
            return redirect()->route('painel.perfil.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/projetos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos /</small> Adicionar Projeto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.projetos.store', 'files' => true]) !!}

        @include('painel.projetos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/projetos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos /</small> Editar Projeto</h2>
    </legend>

    {!! Form::model($projeto, [
        'route'  => ['painel.projetos.update', $projeto->id],
        'method' => 'patch',
        'files'  => true])
    !!}

        @include('painel.projetos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/projetos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('projetos_categoria_id', 'Categoria') !!}
    {!! Form::select('projetos_categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('local', 'Local') !!}
    {!! Form::text('local', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('ano', 'Ano') !!}
    {!! Form::text('ano', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem de Capa') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/projetos/thumbs/'.$projeto->imagem) }}" style="display:block; margin-bottom: 10px; width: 100%; max-width: 500px;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.projetos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/projetos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Projetos
            <a href="{{ route('painel.projetos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Projeto</a>
        </h2>
    </legend>

    <div class="row" style="margin-bottom:20px">
        <div class="form-group col-sm-4">
            {!! Form::select('filtro', $categorias, Input::get('filtro'), ['class' => 'form-control', 'id' => 'filtro-select', 'placeholder' => 'Todas as Categorias', 'data-route' => 'painel/projetos']) !!}
        </div>
        <div class="col-sm-4" style="padding-left:0">
        <a href="{{ route('painel.projetos.categorias.index') }}" class="btn btn-primary btn-md"><span class="glyphicon glyphicon-edit" style="margin-right:10px;"></span><small>Editar Categorias</small></a>
        </div>
        @if(!$filtro)
        <div class="col-sm-4">
            <p class="alert alert-info small" style="margin-bottom: 15px; height:45px; padding: 12px 15px;">
                <span class="glyphicon glyphicon-info-sign" style="margin-right:10px;"></span>
                Selecione uma categoria para ordenar os projetos.
            </p>
        </div>
        @endif
    </div>

    @if(!count($projetos))
    <div class="alert alert-warning" role="alert">Nenhum projeto cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="projetos">
        <thead>
            <tr>
                @if($filtro)<th>Ordenar</th>@endif
                @if(!$filtro)<th>Categoria</th>@endif
                <th>Título</th>
                <th>Capa</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($projetos as $projeto)
            <tr class="tr-row" id="{{ $projeto->id }}">
                @if($filtro)
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                @endif
                @if(!$filtro)
                <td>
                    @if($projeto->categoria->subcategoria) <small>{{ $projeto->categoria->subcategoria }} /</small> @endif @if($projeto->categoria){{ $projeto->categoria->titulo }}@endif
                </td>
                @endif
                <td>
                    {{ $projeto->titulo }}
                </td>
                <td><img src="{{ url('assets/img/projetos/thumbs/'.$projeto->imagem) }}" alt="" style="width:100%;max-width:100px;height:auto;"></td>
                <td><a href="{{ route('painel.projetos.imagens.index', $projeto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.projetos.destroy', $projeto->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.projetos.edit', $projeto->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection