laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('perfil/equipe', ['as' => 'perfil.equipe', 'uses' => 'PerfilController@equipe']);
Route::get('perfil', ['as' => 'perfil', 'uses' => 'PerfilController@index']);
Route::get('projetos/{projetos_categoria_slug?}', ['as' => 'projetos', 'uses' => 'ProjetosController@index']);
Route::get('imprensa', ['as' => 'imprensa', 'uses' => 'ClippingController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);
    Route::resource('equipe', 'EquipeController');
    Route::resource('banners', 'BannersController');
    Route::resource('perfil', 'PerfilController');
    Route::resource('projetos/categorias', 'ProjetosCategoriasController');
    Route::resource('projetos', 'ProjetosController');
    Route::get('projetos/{projetos}/imagens/clear', [
        'as'   => 'painel.projetos.imagens.clear',
        'uses' => 'ProjetosImagensController@clear'
    ]);
    Route::resource('projetos.imagens', 'ProjetosImagensController');
    Route::resource('clipping/imagem', 'ClippingImagemFixaController');
    Route::resource('clipping', 'ClippingController');
    Route::get('clipping/{clipping}/imagens/clear', [
        'as'   => 'painel.clipping.imagens.clear',
        'uses' => 'ClippingImagensController@clear'
    ]);
    Route::resource('clipping.imagens', 'ClippingImagensController');
    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');
    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannerRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'imagem1' => [
            'width'  => 1980,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/banners/1/'
        ],
        'imagem2' => [
            'width'  => 720,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/banners/2/'
        ]
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannerRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem1'] = CropImage::make('imagem1', $this->image_config['imagem1']);
            $input['imagem2'] = CropImage::make('imagem2', $this->image_config['imagem2']);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannerRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem1'])) $input['imagem1'] = CropImage::make('imagem1', $this->image_config['imagem1']);
            if (isset($input['imagem2'])) $input['imagem2'] = CropImage::make('imagem2', $this->image_config['imagem2']);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Helpers\CropImage;

class ClippingController extends Controller
{
    private $image_config = [
        [
            'width'   => 165,
            'height'  => 220,
            'path'    => 'assets/img/clipping/thumbs/'
        ]
    ];

    public function index()
    {
        $clipping = Clipping::ordenados()->get();

        return view('painel.clipping.index', compact('clipping'));
    }

    public function create()
    {
        return view('painel.clipping.create');
    }

    public function store(ClippingRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Clipping::create($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar clipping: '.$e->getMessage()]);

        }
    }

    public function edit(Clipping $clipping)
    {
        return view('painel.clipping.edit', compact('categorias', 'clipping'));
    }

    public function update(ClippingRequest $request, Clipping $clipping)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $clipping->update($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar clipping: '.$e->getMessage()]);

        }
    }

    public function destroy(Clipping $clipping)
    {
        try {

            $clipping->delete();
            return redirect()->route('painel.clipping.index')->with('success', 'Clipping excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir clipping: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagemFixaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingImagemFixaRequest;
use App\Http\Controllers\Controller;

use App\Models\ClippingImagemFixa;
use App\Helpers\CropImage;

class ClippingImagemFixaController extends Controller
{
    private $image_config = [
        'width'  => null,
        'height' => 1280,
        'path'   => 'assets/img/clipping/'
    ];

    public function index()
    {
        $imagem = ClippingImagemFixa::first();

        return view('painel.clipping.imagem', compact('imagem'));
    }

    public function update(ClippingImagemFixaRequest $request, ClippingImagemFixa $imagem)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $imagem->update($input);
            return redirect()->route('painel.clipping.imagem.index')->with('success', 'Imagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Models\ClippingImagem;
use App\Helpers\CropImage;

class ClippingImagensController extends Controller
{
    private $image_config = [
        [
            'width'   => 180,
            'height'  => 180,
            'path'    => 'assets/img/clipping/imagens/thumbs/'
        ],
        [
            'width'   => 1980,
            'height'  => null,
            'upsize'  => true,
            'path'    => 'assets/img/clipping/imagens/'
        ]
    ];

    public function index(Clipping $clipping)
    {
        $imagens = ClippingImagem::clipping($clipping->id)->ordenados()->get();

        return view('painel.clipping.imagens.index', compact('imagens', 'clipping'));
    }

    public function show(Clipping $clipping, ClippingImagem $imagem)
    {
        return $imagem;
    }

    public function create(Clipping $clipping)
    {
        return view('painel.clipping.imagens.create', compact('clipping'));
    }

    public function store(Clipping $clipping, ClippingImagemRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            $input['clipping_id'] = $clipping->id;

            $largura = getimagesize(asset('assets/img/clipping/imagens/'.rawurlencode($input['imagem'])))[0];
            $altura = getimagesize(asset('assets/img/clipping/imagens/'.rawurlencode($input['imagem'])))[1];

            if ($largura <= 0 || $altura <= 0) {
                throw new Exception('Não foi possível identificar as medidas da imagem.');
            }

            $imagem = ClippingImagem::create($input);
            $imagem->largura = $largura;
            $imagem->altura = $altura;
            $imagem->save();

            $view = view('painel.clipping.imagens.imagem', compact('clipping', 'imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Clipping $clipping, ClippingImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }

    public function clear(Clipping $clipping)
    {
        try {

            $clipping->imagens()->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagens excluídas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EquipeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EquipeRequest;
use App\Http\Controllers\Controller;

use App\Models\Equipe;
use App\Helpers\CropImage;

class EquipeController extends Controller
{
    private $image_config = [
        'width'  => 150,
        'height' => 150,
        'path'   => 'assets/img/equipe/'
    ];

    public function index()
    {
        $registros = Equipe::ordenados()->get();

        return view('painel.equipe.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.equipe.create');
    }

    public function store(EquipeRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Equipe::create($input);
            return redirect()->route('painel.equipe.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Equipe $registro)
    {
        return view('painel.equipe.edit', compact('registro'));
    }

    public function update(EquipeRequest $request, Equipe $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $registro->update($input);
            return redirect()->route('painel.equipe.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Equipe $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.equipe.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/PerfilController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PerfilRequest;
use App\Http\Controllers\Controller;

use App\Models\Perfil;
use App\Helpers\CropImage;

class PerfilController extends Controller
{
    private $image_config = [
        'width'  => 1280,
        'height' => null,
        'path'   => 'assets/img/perfil/'
    ];

    public function index()
    {
        $perfil = Perfil::first();

        return view('painel.perfil.index', compact('perfil'));
    }

    public function update(PerfilRequest $request, Perfil $perfil)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $perfil->update($input);
            return redirect()->route('painel.perfil.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>

    <li @if(str_is('painel.perfil*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.perfil.index') }}">Perfil</a>
    </li>

    <li @if(str_is('painel.equipe*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.equipe.index') }}">Equipe</a>
    </li>

    <li @if(str_is('painel.projetos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.projetos.index') }}">Projetos</a>
    </li>

    <li @if(str_is('painel.clipping*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.clipping.index') }}">Imprensa</a>
    </li>

    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url() }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/painel/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/jquery-ui.min.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url() }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/painel/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/bootbox.min.js') }}"></script>
    <script src="{{ asset('assets/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/painel/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/js/painel.js') }}"></script>
</body>
</html>